//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceUsage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblServiceUsage()
        {
            this.tblServiceUsage1 = new HashSet<tblServiceUsage>();
        }
    
        public int Id { get; set; }
        public int User { get; set; }
        public int Service { get; set; }
        public System.DateTime BeginUsage { get; set; }
        public System.DateTime EndUsage { get; set; }
        public int TotalPayment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblServiceUsage> tblServiceUsage1 { get; set; }
        public virtual tblServiceUsage tblServiceUsage2 { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
