//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblService
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortTariffName { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int Price { get; set; }
        public int UsagesCount { get; set; }
    }
}
